/** 디시 입시 갤러리 + 네이버 블로그/카페에서 합격 후기 수집용 검색 쿼리 */
export const ADMISSION_QUERIES = [
  "site:gall.dcinside.com 합격 수능",
  "site:gall.dcinside.com 수시 합격",
  "site:gall.dcinside.com 정시 합격",
  "site:gall.dcinside.com 진학사 칸수",
  "site:gall.dcinside.com 시대인재 합격",
  "site:gall.dcinside.com 한석원 합격",
  "수능 합격 후기",
  "수시 합격 후기",
  "정시 합격 후기",
  "서울대 합격",
  "연세대 합격",
  "고려대 합격",
  "성균관대 합격",
  "한양대 합격",
  "의대 합격 후기",
  "약대 합격 후기",
  "로스쿨 합격",
  "MBA 합격 후기",
  "GKS scholarship admitted",
  "한국 유학 합격 후기",
  "외국인 한국대학 합격",
] as const;
