// 공통 학과 목록 (모든 대학에서 공통 사용)

// 한국 대학 공통 학과
export const KOREAN_MAJORS = [
  // 인문사회계열
  "경제학과",
  "경영학과",
  "경영정보학과",
  "회계학과",
  "금융학과",
  "국제통상학과",
  "법학과",
  "정치외교학과",
  "행정학과",
  "사회학과",
  "심리학과",
  "사회복지학과",
  "언론정보학과",
  "미디어커뮤니케이션학과",
  "광고홍보학과",
  "국어국문학과",
  "영어영문학과",
  "중어중문학과",
  "일어일문학과",
  "독어독문학과",
  "불어불문학과",
  "서어서문학과",
  "러시아어문학과",
  "철학과",
  "역사학과",
  "지리학과",
  "문헌정보학과",
  "사학과",
  "종교학과",
  
  // 공학계열
  "컴퓨터공학부",
  "컴퓨터공학과",
  "소프트웨어학과",
  "전기전자공학과",
  "전기공학과",
  "전자공학과",
  "기계공학과",
  "산업공학과",
  "화학공학과",
  "신소재공학부",
  "신소재공학과",
  "재료공학과",
  "생명공학과",
  "바이오공학과",
  "환경공학과",
  "토목공학과",
  "건축학과",
  "건축공학과",
  "항공우주공학과",
  "조선해양공학과",
  "원자력공학과",
  "에너지공학과",
  "자원에너지공학과",
  "스마트운행체공학과",
  "전기전자컴퓨터",
  "전기전자컴퓨터공학부",
  
  // 자연과학계열
  "수학과",
  "통계학과",
  "물리학과",
  "화학과",
  "생명과학과",
  "생물학과",
  "지구환경과학과",
  "천문우주학과",
  "해양학과",
  "식품영양학과",
  "식품공학과",
  "의류환경학과",
  "의류학과",
  "섬유공학과",
  
  // 의약학계열
  "의과대학의예과",
  "의학과",
  "치의학과",
  "수의학과",
  "약학과",
  "한의학과",
  "간호학과",
  "보건학과",
  "의료공학과",
  "바이오의공학과",
  
  // 예체능계열
  "디자인학과",
  "산업디자인학과",
  "시각디자인학과",
  "미디어디자인학과",
  "미술학과",
  "회화과",
  "조소과",
  "음악학과",
  "성악과",
  "기악과",
  "작곡과",
  "무용학과",
  "체육학과",
  "스포츠과학과",
  "연극영화학과",
  "영화학과",
  "방송학과",
  
  // 교육계열
  "교육학과",
  "유아교육과",
  "초등교육과",
  "국어교육과",
  "영어교육과",
  "수학교육과",
  "과학교육과",
  "사회교육과",
  "체육교육과",
  "음악교육과",
  "미술교육과",
  "지리교육과",
  "역사교육과",
  
  // 기타
  "인문과학계열",
  "공학계열",
  "자연과학계열",
  "예술계열",
  "사범대학",
  "자유전공학부",
  "융합학부",
];

// 미국 대학 공통 학과
export const US_MAJORS = [
  // Business & Economics
  "Business",
  "Business Administration",
  "Economics",
  "Finance",
  "Accounting",
  "Marketing",
  "Management",
  "Entrepreneurship",
  "International Business",
  "MBA",
  "Executive MBA",
  "Part-time MBA",
  "Full-time MBA",
  
  // Engineering
  "Computer Science",
  "Computer Engineering",
  "Software Engineering",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Chemical Engineering",
  "Civil Engineering",
  "Aerospace Engineering",
  "Biomedical Engineering",
  "Environmental Engineering",
  "Industrial Engineering",
  "Materials Science",
  "Engineering",
  
  // Natural Sciences
  "Mathematics",
  "Applied Mathematics",
  "Statistics",
  "Physics",
  "Chemistry",
  "Biology",
  "Biochemistry",
  "Molecular Biology",
  "Neuroscience",
  "Environmental Science",
  "Earth Science",
  "Astronomy",
  "Astrophysics",
  
  // Social Sciences & Humanities
  "Psychology",
  "Political Science",
  "International Relations",
  "International Affairs",
  "Sociology",
  "Anthropology",
  "History",
  "Philosophy",
  "English",
  "Literature",
  "Linguistics",
  "Communications",
  "Journalism",
  "Media Studies",
  
  // Arts
  "Art",
  "Fine Arts",
  "Design",
  "Architecture",
  "Music",
  "Theater",
  "Film",
  "Drama",
  
  // Professional Schools
  "Law School",
  "JD (Juris Doctor)",
  "Medical School",
  "MD (Doctor of Medicine)",
  "Dental School",
  "DDS (Doctor of Dental Surgery)",
  "Pharmacy School",
  "PharmD",
  "Veterinary School",
  "DVM (Doctor of Veterinary Medicine)",
  "Nursing",
  "Public Health",
  "Public Policy",
  "Public Administration",
  "Education",
  "Teaching",
  
  // Interdisciplinary
  "Data Science",
  "Information Systems",
  "Information Technology",
  "Cybersecurity",
  "Artificial Intelligence",
  "Machine Learning",
  "Bioengineering",
  "Biotechnology",
  "Environmental Studies",
  "Sustainability",
  "Urban Studies",
  "Gender Studies",
  "Area Studies",
  "Liberal Arts",
  "General Studies",
];

// 모든 공통 학과 (한국 + 미국)
export const ALL_MAJORS = [
  ...KOREAN_MAJORS,
  ...US_MAJORS,
];

// 중복 제거 및 정렬
export const UNIQUE_MAJORS = Array.from(new Set(ALL_MAJORS)).sort();
